spring.application.name=springboot-4
server.port=8092

# Thymeleaf
spring.thymeleaf.cache=false

# SQL Server - dung cho thuc hanh tren may ca nhan
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=mapper_vd12;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=huy210906
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload
app.upload.product-dir=uploads/products
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
